import os, re

en_base = r"C:\Users\a8881\Desktop\fengyuwang_com\hugo\content\en\blog\posts"

translations = {
    "个人介绍": {
        "body": "My work is built on a core belief: every complex problem can be broken down through a clear logical framework, analysed efficiently with the help of artificial intelligence, and turned into systematic solutions that are reusable, replicable, and actionable.\n\nI offer decision planning and problem-solving services to individuals, entrepreneurs, and businesses, helping clients establish clear judgement in complex environments, reduce risk, optimise pathways, improve efficiency, and achieve long-term goals.\n\nMy service areas cover business development, marketing operations, media and communications, software applications, career development, life planning, and resource allocation.\n\nI am skilled at distinguishing genuine technological innovation from marketing hype, identifying market competition and business risks, and helping clients avoid traps and reduce costly trial and error.\n\nDrawing on systematic analytical frameworks and a broad perspective, combined with AI tools, I integrate trend analysis, historical patterns, and practical logic to deliver executable and verifiable solutions.\n\nI also create content guided by the principle of enhancing human wellbeing, providing valuable information and positive life experiences to society. For inquiries, please contact me at w@fengyu.hk. Fees are charged only after a solution has been proposed and agreed upon."
    },
    "供应强-需求弱": {
        "body": "The core contradiction in the current economy is structural: supply exceeds effective demand. This is not absolute overcapacity across all industries, but a differentiated, squeezing imbalance.\n\nStarting with consumer goods: manufacturing capacity across many sectors is ample. Daily necessities, home appliances, clothing, and ordinary industrial goods are in abundant supply, with prices trending downward and competition intensifying. But the problem is not on the supply side. It is that effective purchasing power cannot keep up. It is not that people do not need these goods. It is that their disposable income is shrinking and their consumption behaviour is contracting.\n\nOn the services side, the situation is equally visible. Too many people have piled into catering, advertising, marketing planning, and new media, while AI-driven substitution has driven down prices for freelance work. More shops open, but the general public spends less frequently, only splurging during holidays, leaving most days quiet.\n\nIf this structure continues to evolve, it forms a self-reinforcing cycle. AI and industry competition reduce white-collar incomes. Lower incomes mean less spending. Less spending means lower revenue for businesses. Lower revenue leads to further lay-offs. More lay-offs mean even lower incomes for more people. The end result is a peculiar state of affairs: goods are abundant, prices are not skyrocketing, but ordinary people feel their purchasing power shrinking.\n\nTwo common misconceptions need correcting. The first is that every industry is in oversupply. In reality, low-end homogeneous supply is indeed excessive, but high-end customised services, specialist healthcare and elderly care, and scarce technical roles remain in strong demand. The second is that a crisis will erupt overnight. In reality, this is a long, slow squeeze. Essential goods remain stable in supply, and there will not be the kind of large-scale collapse seen in classical economic crises.\n\nThe value of understanding this structure is that seeing the trend is more important than working harder in the wrong direction. In an environment where supply exceeds demand, the only way out of the rat race is to move toward higher value-added and scarcer offerings."
    },
    "摇滚比大炮更重要": {
        "body": "If we use two sounds to metaphor the logic of social operation, cannons represent hard commands and rules, while rock n roll represents the impulse for expression and creation.\n\nIn a world of only cannons, all rules are fixed and unquestionable. People do not need to think; they only need to obey. Efficiency may be high, but the room for innovation is zero. In any system with only top-down commands and no bottom-up feedback, the system will eventually ossify.\n\nRock n roll represents an opposing force: questioning, expression, creation. It is not always right, but it provides diversity. Diversity is the fundamental guarantee that a system can adapt and survive when the environment changes.\n\nFrom a logical perspective, cannons maintain order while rock n roll drives evolution. Order and evolution need to coexist. Without order, the system descends into chaos. Without evolution, the system becomes obsolete when the environment shifts. What is needed is a balance between the two, not one overwhelming the other, but leaving room for expression within the framework of order.\n\nThis framework applies to systems at different levels, from national governance to corporate management to personal growth. In any system, preserving a degree of uncontrollable, spontaneous, creative force is a necessary condition for the long-term health of the system.\n\nRock n roll is more important than cannons, not because it is more noble, but because in a rapidly changing world, the speed of evolution determines the probability of survival. And the raw material for evolution never comes from commands. It comes from expression."
    },
    "信任成本决定价格": {
        "body": "The same person, the same service, the same product can sell for dramatically different prices in different channels. This is not an illusion. It is determined by several clear economic principles.\n\nThe first principle is that channels determine pricing power. The same product sold on Xianyu can only fetch Xianyu prices. Sold on Taobao, it fetches Taobao prices. Sold through a high-end consultancy, it commands a professional service fee. The essence of a channel is trust endorsement. The premium customers pay for a channel is essentially payment for trust in that channel.\n\nThe second principle is that trust cost is the highest hidden cost. In an unfamiliar transaction, customers must spend time and effort verifying your authenticity. The higher this verification cost, the lower the price they are willing to pay. Conversely, once trust is established, the premium they are willing to pay rises significantly.\n\nThe third principle is that signalling cost determines the price floor. A high price is itself a signal: expensive means professional, reliable, and trustworthy. A low price sends exactly the opposite signal: cheap means low quality, high risk, and no guarantee. Customers do not evaluate price based on cost. They evaluate it based on signals.\n\nThe fourth principle is that screening costs are ultimately borne by the price. Low prices attract large numbers of low-quality customers who consume more time, make more demands, and generate more disputes. These hidden costs eventually translate into part of your operating costs.\n\nThese four principles reveal a counterintuitive conclusion: in the service industry, a high price is not an obstacle to revenue. It is a tool for screening quality customers, reducing operating costs, and establishing a trust signal."
    },
    "三大企业治理困境": {
        "body": "Three common dilemmas in corporate governance all point to the same root cause: the mismatch between institutional design and human nature.\n\nThe first dilemma is perverse incentives. When a company has no reasonable workload boundaries or incentive mechanisms, the more an employee does, the more tasks they are given. Hard work is not rewarded; it is punished with more work. The result is a reverse incentive: those who work hard lose out, while those who coast are comfortable. Employees actively reduce their output and pretend to be busy, and overall efficiency declines.\n\nThe second dilemma is diffusion of responsibility. In large organisations, everyone feels responsible for only their small piece. When something goes wrong, it is no one person fault. The consequence is that everyone completes their own tasks, but the overall goal is not achieved.\n\nThe third dilemma is short-termism. The evaluation cycle determines behaviour. Quarterly reviews incentivise short-term numbers. Annual reviews cause long-term value to be systematically neglected. When everyone is chasing short-term metrics, the accumulation of long-term competitive advantage is systematically overlooked.\n\nThese three dilemmas share a common root: there is always a gap between what can be measured and what truly matters. Companies measure what is easy to measure, but what truly determines long-term success is hard to measure. This is the measurement paradox: you measure what people do, so people do what you measure, but what you measure is often not what you truly want.\n\nThe direction for resolving these dilemmas is not to design more sophisticated evaluation systems. It is to find a balance: use systems to guarantee minimum standards, and use culture and values to drive excellence."
    },
    "史玉柱逻辑": {
        "body": "Shi Yuzhu business logic can be condensed into one sentence: do not educate, do not debate, do not change. Only identify, only satisfy, only close the deal.\n\nThe core insight behind this approach has three layers.\n\nThe first insight: people are very difficult to persuade. Trying to change someone worldview has infinite cost. Rather than spending time educating those who do not agree with you, find those who already agree.\n\nThe second insight: do not argue with clever people. Give ordinary people the sense of security they want. Shi Yuzhu strategy was never about convincing through logic. It was about using simple, repetitive, emotionally charged messages to penetrate the target audience mind.\n\nThe third insight: cognitive stratification is real. Different groups make decisions differently. High-cognition people decide based on logic and data analysis. Ordinary people decide based on emotion and trust. Using the wrong strategy is inefficient. Using the right strategy is a form of dimensionality reduction.\n\nThis logic corresponds to a classic theory in academia: market segmentation and positioning theory. The idea is not to serve everyone, but to find the best-matched audience and communicate with them in the way that suits them best. Shi Yuzhu uniqueness lies in how he simplified this theory to its extreme: no complex market analysis is needed. Just know clearly who your customers are and what they want.\n\nThe boundary condition for this logic is that its effectiveness depends on the market and audience you choose. If you are in a high-end market dealing with rational decision-makers, this approach may backfire. But if you are in a mass market dealing with ordinary consumers, its effectiveness has been repeatedly proven."
    }
}

for slug, data in translations.items():
    fpath = os.path.join(en_base, slug, "index.md")
    if not os.path.exists(fpath):
        print(f"SKIP: {slug}")
        continue
    
    with open(fpath, "r", encoding="utf-8") as f:
        content = f.read()
    
    parts = content.split("---", 2)
    fm = parts[1]
    
    new_content = "---" + fm + "---\n\n" + data["body"].strip() + "\n"
    
    with open(fpath, "w", encoding="utf-8") as f:
        f.write(new_content)
    
    print(f"OK: {slug}")

print(f"Done! {len(translations)} articles translated")